[package]
name = "pmkam"
description = "GPU Krist vanity address miner based on OpenCL"
version = "0.4.0"
authors = ["miguel"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
ocl = "0.19.3"
ocl-extras = "0.1.1"
getrandom = "0.1.14"
sha2 = "0.9.1"
